import { useCallback, useEffect, useState } from "react";
import { usingMockApi, verifyBib } from "../api/client";
import type { BibFieldStatus, BibVerifyResponse, PaperRecord } from "../types/api";
import { Icon } from "./Icon";

interface BibVerificationModalProps {
  bib: PaperRecord | null;
  sourcePapers: PaperRecord[];
  onClose: () => void;
}

const fieldStatusLabels: Record<BibFieldStatus, string> = {
  MATCH: "Match",
  MISMATCH: "Mismatch",
  BIB_MISSING: "Missing in Bib",
  PDF_MISSING: "PDF metadata unavailable",
  NOT_CHECKED: "Not checked",
};

export function BibVerificationModal({ bib, sourcePapers, onClose }: BibVerificationModalProps) {
  const [result, setResult] = useState<BibVerifyResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const runVerification = useCallback(async (signal?: AbortSignal) => {
    if (!bib) return;
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const response = await verifyBib(
        bib.paper_id,
        sourcePapers.map((paper) => paper.paper_id),
        signal,
      );
      if (!signal?.aborted) setResult(response);
    } catch (requestError) {
      if (signal?.aborted) return;
      setError(requestError instanceof Error ? requestError.message : "Unable to verify BibTeX metadata.");
    } finally {
      if (!signal?.aborted) setLoading(false);
    }
  }, [bib, sourcePapers]);

  useEffect(() => {
    if (!bib) return;
    const controller = new AbortController();
    void runVerification(controller.signal);
    return () => controller.abort();
  }, [bib, runVerification]);

  useEffect(() => {
    if (!bib) return;
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
    };
    window.addEventListener("keydown", closeOnEscape);
    return () => window.removeEventListener("keydown", closeOnEscape);
  }, [bib, onClose]);

  if (!bib) return null;

  const warningCount = result?.results.reduce((total, entry) => total + entry.warning_count, 0) || 0;
  const hasPdfMissing = result?.results.some((entry) =>
    entry.fields.some((field) => field.status === "PDF_MISSING"),
  );

  return (
    <div className="library-upload-overlay" role="presentation" onMouseDown={(event) => {
      if (event.currentTarget === event.target) onClose();
    }}>
      <section className="bib-verification-modal" role="dialog" aria-modal="true" aria-labelledby="bib-verification-title">
        <header className="library-upload-heading">
          <div>
            <span className="eyebrow">BibTeX metadata</span>
            <h2 id="bib-verification-title">Verify {bib.original_filename}</h2>
            <p>Comparing {bib.entry_count} {bib.entry_count === 1 ? "entry" : "entries"} with metadata from {sourcePapers.length} completed {sourcePapers.length === 1 ? "PDF" : "PDFs"}.</p>
          </div>
          <button className="icon-button" type="button" aria-label="Close BibTeX verification" onClick={onClose}><Icon name="x" /></button>
        </header>

        <div className="bib-verification-content">
          {usingMockApi && (
            <div className="library-mode-notice demo" role="status">
              <Icon name="spark" size={18} />
              <div><strong>Demo metadata preview</strong><p>This result is generated by the Mock API and is not a real backend verification.</p></div>
            </div>
          )}

          {loading && (
            <div className="bib-verification-state" role="status">
              <span className="spinner" />
              <div><strong>Checking bibliography metadata</strong><p>Sending this BibTeX record and the available PDF IDs to the backend.</p></div>
            </div>
          )}

          {!loading && error && (
            <div className="bib-verification-error" role="alert">
              <Icon name="x" size={18} />
              <div><strong>Verification failed</strong><p>{error}</p><button className="button button-secondary" type="button" onClick={() => void runVerification()}>Try again</button></div>
            </div>
          )}

          {!loading && result && (
            <>
              <div className="bib-verification-summary">
                <div><span>Total entries</span><strong>{result.total_entries}</strong></div>
                <div><span>Fully matched</span><strong>{result.matched_entries}</strong></div>
                <div><span>Entries with errors</span><strong>{result.error_entries}</strong></div>
                <div><span>Warnings</span><strong>{warningCount}</strong></div>
              </div>

              {hasPdfMissing && (
                <div className="bib-pdf-missing-note" role="status">
                  <Icon name="document" size={19} />
                  <div><strong>Some PDF metadata is unavailable</strong><p><code>PDF_MISSING</code> means the parser did not return metadata for comparison. The BibTeX file and verification request still completed successfully.</p></div>
                </div>
              )}

              <div className="bib-entry-list">
                {result.results.map((entry) => (
                  <details className="bib-entry-result" key={entry.citation_key} open={result.results.length === 1}>
                    <summary>
                      <span><code>{entry.citation_key}</code><small>{entry.summary}</small></span>
                      <span className={entry.has_errors ? "bib-entry-health error" : entry.warning_count > 0 ? "bib-entry-health warning" : "bib-entry-health success"}>
                        {entry.error_count > 0 ? `${entry.error_count} errors` : entry.warning_count > 0 ? `${entry.warning_count} warnings` : "Matched"}
                      </span>
                    </summary>
                    <div className="bib-field-list">
                      {entry.fields.map((field) => (
                        <article className="bib-field-result" key={`${entry.citation_key}-${field.field_name}`}>
                          <header><strong>{field.field_name}</strong><span className={`bib-field-status bib-status-${field.status.toLowerCase()}`}>{fieldStatusLabels[field.status]}</span></header>
                          <dl>
                            <div><dt>BibTeX</dt><dd>{field.bib_value || "Not provided"}</dd></div>
                            <div><dt>PDF</dt><dd>{field.pdf_value || "Not available"}</dd></div>
                          </dl>
                          {field.detail && <p>{field.detail}</p>}
                        </article>
                      ))}
                    </div>
                  </details>
                ))}
              </div>
            </>
          )}
        </div>

        <footer className="library-upload-footer">
          <span><Icon name="shield" size={16} /> Results come from the configured Bib verification endpoint.</span>
          <button className="button button-primary" type="button" onClick={onClose}>Close</button>
        </footer>
      </section>
    </div>
  );
}
